### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by nfrechette** [nfrechette/sjson-cpp#3]
Add unit tests along with cmake support to generate the solution.
See [ACL](https://github.com/nfrechette/acl)

**Comment by AnisB** [comment]
Do you have a preference regarding the unit test framework?

**Comment by nfrechette** [comment]
In ACL and Gin, I use [Catch](https://github.com/philsquared/Catch). It works pretty well. ACL has a good example of what I have in mind integration wise.
